services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    ports:
      - 2375:2375
    environment:
      CONTAINERS: 1
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - socket-proxy
networks:
  socket-proxy:
    name: socket-proxy
